training = [
('5 BRIDGE STREET',['StreetNumber', 'StreetName', 'StreetName']),
('9 PRINCES SQUARE',['StreetNumber', 'StreetName', 'StreetName']),
('THE STUDIO HATHERLOW HOUSE HATHERLOW',['Building', 'Building', 'Building', 'Building', 'StreetName']),
('71-75 SHELTON STREET',['StreetNumber', 'StreetName', 'StreetName']),
('372 OLD STREET 335 ROSDEN HOUSE',['StreetNumber', 'StreetName', 'StreetName', 'Unit', 'Building', 'Building']),
('OLD BARN FARM HARTFIELD ROAD',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('1ST AND 2ND FLOORS ELIZABETH HOUSE LES RUETIES BRAYES',['Floor', 'Floor', 'Floor', 'Floor', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('UNIT 9 BERRY COURT FARM BRAMLEY ROAD LITTLE LONDON',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Village', 'Village']),
('26 CARMICHAEL CLOSE WINSTANLEY ESTATE',['StreetNumber', 'StreetName', 'StreetName', 'Estate', 'Estate']),
('FANE COURT GREEN ROAD SHIPBOURNE',['Building', 'Building', 'StreetName', 'StreetName', 'Village']),
('38 PAXTON GARDENS WOKING',['StreetNumber', 'StreetName', 'StreetName', 'Town']),
('OFFICE 221 CEME CAMPUS MARSH WAY',['Unit', 'Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('94-96 SEYMOUR PLACE',['StreetNumber', 'StreetName', 'StreetName']),
('0/2 26 BRISBANE STREET',['Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('16 BROADWAY AVENUE',['StreetNumber', 'StreetName', 'StreetName']),
('13 RUTLAND STREET',['StreetNumber', 'StreetName', 'StreetName']),
('197 CLAREMONT ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('HOLLY HOUSE 220 NEW LONDON ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('C/O CHARNWOOD ACCOUNTANTS THE POINT GRANITE WAY MOUNTSORREL',['CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetName', 'StreetName', 'Village']),
('MR.E.SZELICZYK 67 OXLEAY ROAD',['CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('20-22 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('VANTAGE POINT 23 MARK ROAD',['CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('43A UXBRIDGE ROAD LONDON',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('33 BEECHBANK NORWICH',['StreetNumber', 'StreetName', 'City']),
('ST ANN\'S HOUSE ST ANN\'S STREET',['Building', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('POST OFFICE 14 SOUTH STREET TILLINGHAM',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Village']),
('C/O CLARKE BELL LIMITED 3RD FLOOR THE PINNACLE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Floor', 'Floor', 'Building', 'Building']),
('17 CANNON PLACE HAMPSTEAD',['StreetNumber', 'StreetName', 'StreetName', 'Town']),
('GOLEUFAN 27 CHESTER STREET',['CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('CHANNING SCHOOL HIGHGATE HILL',['CareOf', 'CareOf', 'StreetName', 'StreetName']),
('4 BADGERS CROFT VICTORIA ROAD MORTIMER COMMON',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'Village', 'Village']),
('KEYES HOUSE 9 ORCHARD TERRACE',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('386 DUKE STREET',['StreetNumber', 'StreetName', 'StreetName']),
('THE COOPER BUILDING 505 GREAT WESTERN ROAD',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('2 GROSVENOR SQUARE',['StreetNumber', 'StreetName', 'StreetName']),
('50 EGERTON GARDENS',['StreetNumber', 'StreetName', 'StreetName']),
('FLAT 9 METROPOLITAN COURT 6 HAYLING WAY',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('590 KINGSTON ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('UNIT 1A 10 STOUR ROAD',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('5 WOLSEY PARADE SHERBURN IN ELMET',['StreetNumber', 'StreetName', 'StreetName', 'Town', 'Town', 'Town']),
('7 GRANARD BUSINESS CENTRE BUNNS LANE',['Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('291 WATLING STREET',['StreetNumber', 'StreetName', 'StreetName']),
('77 CASTLE HILL DRIVE EBBSFLEET VALLEY',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Town', 'Town']),
('86-90 PAUL STREET',['StreetNumber', 'StreetName', 'StreetName']),
('1 A PENDELL AVENUE',['Unit', 'Unit', 'StreetName', 'StreetName']),
('1A BRICK COURT JETTY WALK',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('19 DARBY CRESCENT',['StreetNumber', 'StreetName', 'StreetName']),
('BEN-GURION AIRPORT PO BOX 41',['Building', 'Building', 'POBox', 'POBox', 'POBox']),
('GROVE HOUSE THIRD FLOOR LOWLANDS ROAD',['Building', 'Building', 'Floor', 'Floor', 'StreetName', 'StreetName']),
('KING STREET HOUSE 15 UPPER KING STREET',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('SMOLYAN 7 BULGARIA BLVD. 2ND FLOOR',['Town', 'StreetNumber', 'StreetName', 'StreetName', 'Floor', 'Floor']),
('110 MIDDLETON AVENUE MIDDLETON AVENUE',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('THE PRINCE OF WALES HOSPICE HALFPENNY LANE',['Building', 'Building', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('135 REDDENHILL ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('STUBENRING 18 A-1010 VIENNA',['StreetName', 'StreetNumber', 'PostCode', 'City']),
('C/O THORNE LANCASTER PARKER VENTURE HOUSE 27-29 GLASSHOUSE STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('RAILWAY ARCH 102A ROCKINGHAM STREET',['Building', 'Building', 'Unit', 'StreetName', 'StreetName']),
('FLAT 6 50 ROMAN ROAD',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('57 CHISWELL ST. LONDON E.C.1.',['StreetNumber', 'StreetName', 'StreetName', 'City', 'PostCode']),
('61 DOWNSWAY SOUTHWICK',['StreetNumber', 'StreetName', 'Town']),
('THE STATION HOUSE 15 STATION ROAD',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('6TH FLOOR 5 ALDERMANBURY SQUARE',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('671 SPUR ROAD NORTH FELTHAM TRADING ESTATE',['StreetNumber', 'StreetName', 'StreetName', 'Estate', 'Estate', 'Estate', 'Estate'])]