test = [('KARELEAN COURT CHARLTON MEAD DRIVE',['Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
        ('7 COSFORD CLOSE',['StreetNumber', 'StreetName', 'StreetName']),
        ('29 PRINCES DRIVE',['StreetNumber', 'StreetName', 'StreetName']),
        ('128 CITY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
        ('HORSE + BAMBOO 679 BACUP ROAD WATERFOOT',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
        ('132 BELHAVEN PARK HEATHFIELD GRANGE',['StreetNumber', 'StreetName', 'StreetName', 'Building', 'Building']),
        ('C/O RAYNERS THE OLD PARISH HALL',['CareOf', 'CareOf', 'Building', 'Building', 'Building', 'Building']),
        ('28 VICTORIA PLACE BRIGHTLINGSEA',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
        ('124-128 CITY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
        ('ELDRIDGE COURT FLAT 7 ROUEL ROAD',['Building', 'Building', 'Unit', 'Unit', 'StreetName', 'StreetName']),
        ('CITY GATES 2-4 SOUTHGATE',['Building', 'Building', 'StreetNumber', 'StreetName']),
        ('UNIT 8 DRY DRAYTON INDUSTRIES SCOTLAND ROAD',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
        ('72 QUEENS ROAD',['StreetNumber', 'StreetName', 'StreetName']),
        ('MIRADOR CANNON COURT ROAD',['Building', 'StreetName', 'StreetName', 'StreetName']),
        ('5 IVEGATE YEADON',['StreetNumber', 'StreetName', 'Locality']),
        ('2 DEPOZITELOR STREET SEBES TOWN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
        ('BELLE VUE WORKS BOUNDARY STREET',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
        ('FLAT 1 MARLOW COURT COLINDEEP LANE',['Unit', 'Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
        ('ASSOCIATES HOUSE 118A EAST BARNET ROAD',['Building', 'Building', 'Unit', 'StreetName', 'StreetName', 'StreetName']),
        ('7 BELL YARD',['StreetNumber', 'StreetName', 'StreetName']),
        ('34 FAIRLAWNS',['StreetNumber', 'StreetName']),
        ('77 VALLEY DRIVE',['StreetNumber', 'StreetName', 'StreetName']),
        ('1 BEACONSFIELD 64 RED LION STREET',['Unit', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
        ('20 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
        ('ISM MAGAZINE 272 BATH STREET',['CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
        ('34 PLASHET GROVE',['StreetNumber', 'StreetName', 'StreetName']),
        ('664 OLDHAM ROAD FAILSWORTH',['StreetNumber', 'StreetName', 'StreetName', 'Locality'])
        ]