training = [
('5 BRIDGE STREET',['StreetNumber', 'StreetName', 'StreetName']),
('9 PRINCES SQUARE',['StreetNumber', 'StreetName', 'StreetName']),
('THE STUDIO HATHERLOW HOUSE HATHERLOW',['Building', 'Building', 'Building', 'Building', 'StreetName']),
('71-75 SHELTON STREET',['StreetNumber', 'StreetName', 'StreetName']),
('372 OLD STREET 335 ROSDEN HOUSE',['StreetNumber', 'StreetName', 'StreetName', 'Unit', 'Building', 'Building']),
('OLD BARN FARM HARTFIELD ROAD',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('1ST AND 2ND FLOORS ELIZABETH HOUSE LES RUETIES BRAYES',['Floor', 'Floor', 'Floor', 'Floor', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('UNIT 9 BERRY COURT FARM BRAMLEY ROAD LITTLE LONDON',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('26 CARMICHAEL CLOSE WINSTANLEY ESTATE',['StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others']),
('FANE COURT GREEN ROAD SHIPBOURNE',['Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('38 PAXTON GARDENS WOKING',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('OFFICE 221 CEME CAMPUS MARSH WAY',['Unit', 'Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('94-96 SEYMOUR PLACE',['StreetNumber', 'StreetName', 'StreetName']),
('0/2 26 BRISBANE STREET',['Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('16 BROADWAY AVENUE',['StreetNumber', 'StreetName', 'StreetName']),
('13 RUTLAND STREET',['StreetNumber', 'StreetName', 'StreetName']),
('197 CLAREMONT ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('HOLLY HOUSE 220 NEW LONDON ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('C/O CHARNWOOD ACCOUNTANTS THE POINT GRANITE WAY MOUNTSORREL',['CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('MR.E.SZELICZYK 67 OXLEAY ROAD',['CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('20-22 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('VANTAGE POINT 23 MARK ROAD',['CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('43A UXBRIDGE ROAD LONDON',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('33 BEECHBANK NORWICH',['StreetNumber', 'StreetName', 'City']),
('ST ANN\'S HOUSE ST ANN\'S STREET',['Building', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('POST OFFICE 14 SOUTH STREET TILLINGHAM',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('C/O CLARKE BELL LIMITED 3RD FLOOR THE PINNACLE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Floor', 'Floor', 'Building', 'Building']),
('17 CANNON PLACE HAMPSTEAD',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('GOLEUFAN 27 CHESTER STREET',['CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('CHANNING SCHOOL HIGHGATE HILL',['CareOf', 'CareOf', 'StreetName', 'StreetName']),
('4 BADGERS CROFT VICTORIA ROAD MORTIMER COMMON',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('KEYES HOUSE 9 ORCHARD TERRACE',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('386 DUKE STREET',['StreetNumber', 'StreetName', 'StreetName']),
('THE COOPER BUILDING 505 GREAT WESTERN ROAD',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('2 GROSVENOR SQUARE',['StreetNumber', 'StreetName', 'StreetName']),
('50 EGERTON GARDENS',['StreetNumber', 'StreetName', 'StreetName']),
('FLAT 9 METROPOLITAN COURT 6 HAYLING WAY',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('590 KINGSTON ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('UNIT 1A 10 STOUR ROAD',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('5 WOLSEY PARADE SHERBURN IN ELMET',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality', 'Locality']),
('7 GRANARD BUSINESS CENTRE BUNNS LANE',['Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('291 WATLING STREET',['StreetNumber', 'StreetName', 'StreetName']),
('77 CASTLE HILL DRIVE EBBSFLEET VALLEY',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('86-90 PAUL STREET',['StreetNumber', 'StreetName', 'StreetName']),
('1 A PENDELL AVENUE',['Unit', 'Unit', 'StreetName', 'StreetName']),
('1A BRICK COURT JETTY WALK',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('19 DARBY CRESCENT',['StreetNumber', 'StreetName', 'StreetName']),
('BEN-GURION AIRPORT PO BOX 41',['Building', 'Building', 'POBox', 'POBox', 'POBox']),
('GROVE HOUSE THIRD FLOOR LOWLANDS ROAD',['Building', 'Building', 'Floor', 'Floor', 'StreetName', 'StreetName']),
('KING STREET HOUSE 15 UPPER KING STREET',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('SMOLYAN 7 BULGARIA BLVD. 2ND FLOOR',['Locality', 'StreetNumber', 'StreetName', 'StreetName', 'Floor', 'Floor']),
('110 MIDDLETON AVENUE MIDDLETON AVENUE',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('THE PRINCE OF WALES HOSPICE HALFPENNY LANE',['Building', 'Building', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('135 REDDENHILL ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('STUBENRING 18 A-1010 VIENNA',['StreetName', 'StreetNumber', 'PostCode', 'City']),
('C/O THORNE LANCASTER PARKER VENTURE HOUSE 27-29 GLASSHOUSE STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('RAILWAY ARCH 102A ROCKINGHAM STREET',['Building', 'Building', 'Unit', 'StreetName', 'StreetName']),
('FLAT 6 50 ROMAN ROAD',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('57 CHISWELL ST. LONDON E.C.1.',['StreetNumber', 'StreetName', 'StreetName', 'City', 'PostCode']),
('61 DOWNSWAY SOUTHWICK',['StreetNumber', 'StreetName', 'Locality']),
('THE STATION HOUSE 15 STATION ROAD',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('6TH FLOOR 5 ALDERMANBURY SQUARE',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('671 SPUR ROAD NORTH FELTHAM TRADING ESTATE',['StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others', 'Others', 'Others']),
('PALMERSTON HOUSE 814 BRIGHTON ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('3RD FLOOR 114A CROMWELL ROAD',['Floor', 'Floor', 'Unit', 'StreetName', 'StreetName']),
('19 SMITH\'S PLACE LEITH WALK',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('11 HAREWOOD AVENUE LONDON',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('8 THE OLD HAYBARN',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('WEST WALK 1A BOWES OFFICES LAMBTON PARK',['StreetName', 'StreetName', 'Unit', 'Building', 'Building', 'Locality', 'Locality']),
('603 LORDSHIP LANE WOOD GREEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('16-18 WEST STREET THE SQUARE',['StreetNumber', 'StreetName', 'StreetName', 'Building', 'Building']),
('UNIT 7 JETSTREAM DRIVE AUCKLEY',['Unit', 'Unit', 'StreetName', 'StreetName', 'Locality']),
('BRIDGE HOUSE 74 BROAD STREET',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('97 JUDD STREET',['StreetNumber', 'StreetName', 'StreetName']),
('6-9 THE SQUARE STOCKLEY PARK',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('OLD LINEN COURT 83-85 SHAMBLES STREET',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('1 ST EDMUNDS HALL DUNCOMBE STREET',['Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('55 WOODLEIGH AVENUE',['StreetNumber', 'StreetName', 'StreetName']),
('\"STREONSHALH\" KHYBER PASS',['CareOf', 'StreetName', 'StreetName']),
('C/O DRAGON COWORKING 7/8 NEW ROAD AVENUE',['CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('109 ASHTREE ROAD TIVIDALE',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('FLAT 2 THE BEECHES 10 GUILDOWN ROAD',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('1 LONGFIELD COURT',['StreetNumber', 'StreetName', 'StreetName']),
('ST JAMES CE PRIMARY SCHOOL CHADWICK STREET',['Building', 'Building', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('44 THE UPLANDS DUKES WOOD',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('1 BURNHAM CHASE',['StreetNumber', 'StreetName', 'StreetName']),
('4A BEACON ROAD GREAT BARR',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('ACORN ESTATE MANAGEMENT 9 ST MARKS ROAD',['CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('358 BRIGHTON ROAD BRIGHTON ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('11-10 ELIZABETES IELA',['StreetNumber', 'StreetName', 'StreetName']),
('101 RYDES HILL ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('C/O PARRY PROPERTY MANAGEMENT 80 HIGH STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('75 MANOR ROAD SELSEY',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('THE OLD VICARAGE MAIN ROAD BIDDENHAM',['Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('18 ASPINALL CLOSE BEKESBOURNE',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('1 THE WARREN HORSHAM ROAD HANDCROSS',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('47 STUART ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('THE LOFT UNIT 11 HUNTHAY BUSINESS PARK',['Building', 'Building', 'Unit', 'Unit', 'Others', 'Others', 'Others']),
('48 - 52 PENNY LANE MOSSLEY HILL',['StreetNumber', 'StreetNumber', 'StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('VALLEY DRIVE',['StreetName', 'StreetName']),
('ERWIN HYMER CENTRE (TRAVELWORLD) VALLEY DRIVE',['Building', 'Building', 'Building', 'Building','StreetName', 'StreetName']),
('15 WINFORD COURT PORTBURY CLOSE PECKHAM',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('34-36 HARBOUR ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('412 GT HORTON ROAD BRADFORD 7',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('45A ELMGROVE ROAD',['Unit', 'StreetName', 'StreetName']),
('PARSONS COURT 9 SOUTHDOWN ROAD MILLBROOK',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('8 JURY STREET',['StreetNumber', 'StreetName', 'StreetName']),
('1 MORE LONDON PLACE LONDON',['Building', 'Building', 'Building', 'Building', 'City']),
('BECKET HOUSE 1 LAMBETH PALACE ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('59 CALDON HOUSE WAXLOW WAY',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('123 MARSHALL LANE',['StreetNumber', 'StreetName', 'StreetName']),
('5 BROGDEN STREET',['StreetNumber', 'StreetName', 'StreetName']),
('EAGLES REST WOODSPEEN',['Others', 'Others', 'Locality']),
('ESTATE OFFICE LAMBS FARM BUSINESS PARK BASINGSTOKE ROAD SWALLOWFIELD',['Building', 'Building', 'Others', 'Others', 'Others', 'Others', 'StreetName', 'StreetName', 'Locality']),
('47 DELVES CRESCENT',['StreetNumber', 'StreetName', 'StreetName']),
('89 SEAWARD STREET',['StreetNumber', 'StreetName', 'StreetName']),
('18 ELDON GARDEN PERCY STREET',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('2 STEEPLE COURT HOLT ROAD',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('FLAT 9 WYATT PARK MANSIONS STREATHAM HILL',['Unit', 'Unit', 'Building', 'Building', 'Building', 'Locality', 'Locality']),
('296 HALL LANE',['StreetNumber', 'StreetName', 'StreetName']),
('9 PRINCES SQUARE',['StreetNumber', 'StreetName', 'StreetName']),
('20 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('DALTON HOUSE 60 WINDSOR AVENUE',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('78 LOWER REEVE GREAT CORNARD',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('9 PRINCES SQUARE',['StreetNumber', 'StreetName', 'StreetName']),
('81A GALGORM ROAD',['Unit', 'StreetName', 'StreetName']),
('AP 197 58 THE BANKSHEEPCOTE STREET',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('3 CUTTERS ROW',['StreetNumber', 'StreetName', 'StreetName']),
('128 CITY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('VICTORY HOUSE 17/19 MARINO WAY HOGWOOD INDUSTRIAL ESTATE',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others', 'Others']),
('17 WHALEBONE LANE SOUTH',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('1ST FLOOR 104 OXFORD STREET',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('4 CARTERS CLOSE',['StreetNumber', 'StreetName', 'StreetName']),
('1580 PARKWAY SOLENT BUSINESS PARK WHITELEY',['Building', 'Building', 'Others', 'Others', 'Others', 'Locality']),
('OAKS COTTAGE HERSHAM FARM BUSINESS PARK LONGCROSS ROAD',['Building', 'Building', 'Others', 'Others', 'Others', 'Others', 'StreetName', 'StreetName']),
('128 CITY ROAD CITY ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('12 HATHERLEY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('59 PARK VIEW',['StreetNumber', 'StreetName', 'StreetName']),
('29 GILDREDGE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('UNIT 29 HIGHCROFT INDUSTRIAL ESTATE ENTERPRISE ROAD HORNDEAN',['Unit', 'Unit', 'Others', 'Others', 'Others', 'StreetName', 'StreetName', 'Locality']),
('17 MANN ISLAND',['StreetNumber', 'StreetName', 'StreetName']),
('1ST FLOOR THE SYMS BUILDING BUMPERS WAY BUMPERS FARM',['Floor', 'Floor', 'Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Others', 'Others']),
('21 SOUTH ROAD HAGLEY',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('6 POOLE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('786 LONDON ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('2 BRIDGE BANK CLOSE STONE CROSS PARK',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Others', 'Others', 'Others']),
('MARIA HOUSE 35 MILLERS ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('116 ASHLEY ROAD HALE',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('23 C/O SEVERIN FINANCE DORSET ROAD',['StreetNumber', 'CareOf', 'CareOf', 'CareOf', 'StreetName', 'StreetName']),
('12 FRATTON ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('19 WARREN PARK WAY ENDERBY',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Locality']),
('71-75 SHELTON STREET COVENT GARDEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('20 ABBOTS BUSINESS PARK PRIMROSE HILL',['Unit', 'Others', 'Others', 'Others', 'Locality', 'Locality']),
('1- 11 ALVIN STREET ALVIN STREET',['StreetNumber', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('HEASLEY HOUSE HEASLEY MILL',['Building', 'Building', 'Locality', 'Locality']),
('20 KING STREET MORLEY',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('ST JOHNS HOUSE 16 CHURCH STREET',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('13-14 BLACKHEATH GROVE',['StreetNumber', 'StreetName', 'StreetName']),
('CREATE BUSINESS HUB GROUND FLOOR 5 RAYLEIGH ROAD HUTTON',['Others', 'Others', 'Others', 'Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('37 EDINBURGH AVENUE',['StreetNumber', 'StreetName', 'StreetName']),
('C/O THE ACCOUNTING CREW LIMITED 85 TOTTENHAM COURT ROAD',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('UNIT A6 CHAUCER BUSINESS PARK DITTONS ROAD',['Unit', 'Unit', 'Others', 'Others', 'Others', 'StreetName', 'StreetName']),
('PLUMMER FARM PLUMMER LANE',['Others', 'Others', 'StreetName', 'StreetName']),
('1 VICARAGE LANE',['StreetNumber', 'StreetName', 'StreetName']),
('BRAMHALL HOUSE 14 ACK LANE EAST BRAMHALL',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Locality']),
('FIRST FLOOR 105-111 EUSTON STREET',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('85 GREAT PORTLAND STREET FIRST FLOOR',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Floor', 'Floor']),
('UNIT A 10 FASHION STREET',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('82A JAMES CARTER ROAD',['Unit', 'StreetName', 'StreetName', 'StreetName']),
('23A ST. ANN\'S ROAD',['Unit', 'StreetName', 'StreetName', 'StreetName']),
('231A HULLBRIDGE ROAD SOUTH WOODHAM FERRERS',['Unit', 'StreetName', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('METASI HOUSE WEST STREET',['Building', 'Building', 'StreetName', 'StreetName']),
('FLAT B 93 KING HENRY\'S ROAD PRIMROSE HILL',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('76 SYDENHAM ROAD SYDENHAM ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('THE COACH HOUSE THE SQUARE',['Building', 'Building', 'Building', 'Locality', 'Locality']),
('17 ST. JOHN STREET WIRKSWORTH',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Locality']),
('FLAT 6 BROADSIDE HOUSE 3 COMET STREET',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('12 HATHERLEY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('102 MITCHAM LANE',['StreetNumber', 'StreetName', 'StreetName']),
('1125 LONDON ROAD LONDON ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('67 KENSINGTON GARDENS SQUARE FLAT 2',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Unit', 'Unit']),
('93 TABERNACLE STREET',['StreetNumber', 'StreetName', 'StreetName']),
('19 MORLAND WAY CHESHUNT',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('ROSE COTTAGE 15 NORTH FEN ROAD GLINTON',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Locality']),
('STABLE BARN LENBOROUGH ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('&DEV LTD ORWELL HOUSE COWLEY ROAD',['CareOf', 'CareOf', 'Building', 'Building', 'StreetName', 'StreetName']),
('UNIT 1 THE SIDINGS VICTORIA AVENUE IND ESTATE',['Unit', 'Unit', 'Building', 'Building', 'Others', 'Others', 'Others', 'Others']),
('61A MATTISON ROAD',['Unit', 'StreetName', 'StreetName']),
('PO BOX 1233',['POBox', 'POBox', 'POBox']),
('THE OLD COTTAGE MILL CORNER',['Building', 'Building', 'Building', 'Locality', 'Locality']),
('DEERWOOD HOUSE DAVID AVENUE',['Building', 'Building', 'StreetName', 'StreetName']),
('6 MAPLE GROVE BUSINESS CENTRE LAWRENCE ROAD',['Unit', 'Building', 'Building', 'Building', 'Building','StreetName', 'StreetName']),
('MONOMETER HOUSE RECTORY GROVE',['Building', 'Building', 'StreetName', 'StreetName']),
('THE CURLEWS LAKE LANE FRAMPTON ON SEVERN',['Building', 'Building', 'StreetName', 'StreetName', 'Locality', 'Locality', 'Locality']),
('55 CRINGLE DRIVE',['StreetNumber', 'StreetName', 'StreetName']),
('20-22 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('FORESTERS HALL 25-27 WESTOW STREET',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('GRAHAM HILLS BUILDING C/O STRATHCLYDE UNIVERSITY INCUBATOR LTD 50 RICHMOND STREET',['Building', 'Building', 'Building', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('316 GROVE GREEN ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('30-34 NORTH STREET',['StreetNumber', 'StreetName', 'StreetName']),
('FLAT 7B ST JOHNS ROAD BRAZILL MILL COURT BRAZIL MILL COURT',['Unit', 'Unit', 'StreetName', 'StreetName', 'StreetName', 'Building', 'Building', 'Building', 'Building', 'Building', 'Building']),
('23A BROAD LANE',['Unit', 'StreetName', 'StreetName']),
('3 ST. CLEMENTS AVENUE',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('1168/1170 MELTON ROAD SYSTON',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('1 SOUTH PARADE',['StreetNumber', 'StreetName', 'StreetName']),
('71-75 SHELTON STREET COVENT GARDEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('C/O TAXASSIST ACCOUNTANTS 89 TOWN STREET HORSFORTH',['CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('UNIT 2 GREEN PARK COAL ROAD',['Unit', 'Unit', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('KINGSCOTT DIX CHELTENHAM LTD MALVERN VIEW BUSINESS PARK',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Others', 'Others', 'Others', 'Others']),
('FINSGATE 5-7 CRANWOOD STREET',['Building', 'StreetNumber', 'StreetName', 'StreetName']),
('6 REDHEUGHS RIGG',['StreetNumber', 'StreetName', 'StreetName']),
('ST. MARYS LODGE NEW WALK',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('22 YORK BUILDINGS JOHN ADAM STREET',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('C/O RESOLVE ADVISORY LIMITED 22 YORK BUILDINGS',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Unit', 'Building', 'Building']),
('45-47 LOWER CLAPTON ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('179 BROCKLEY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('17 VICTORIA ROAD EAST',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('FOCUS HOUSE HAM ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('84 CHINGFORD AVENUE CHINGFORD',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('66 WOODLANDS ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('71-75 SHELTON STREET COVENT GARDEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('184 HENLEAZE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('57 SOUTHEND ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('C/O INTOUCH ACCOUNTING EVERDENE HOUSE DEANSLEIGH ROAD',['CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetName', 'StreetName']),
('ZEETA HOUSE 200 UPPER RICHMOND ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('SUSSEX INNOVATION CENTRE SCIENCE PARK SQUARE',['Building', 'Building', 'Building', 'Others', 'Others', 'Others']),
('3 THE COURTYARD HARRIS BUSINES PARK HANBURY ROAD STOKE PRIOR',['Unit', 'Building', 'Building', 'Others', 'Others', 'Others', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('MIDWAY HOUSE HERRICK WAY STAVERTON',['Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('4 MILL CLOSE LLANISHEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('3 LAYCHEQUERS MEADOW TAPLOW',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('UNIT 1 HEYWORTH BUSINESS PARK OLD PORTSMOUTH ROAD',['Unit', 'Unit', 'Others', 'Others', 'Others', 'StreetName', 'StreetName', 'StreetName']),
('UNIT 3 EARLSFIELD BUSINESS CENTRE 9 LYDDEN ROAD',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('14 THOMAS COULTER HOUSE 1 SHIPWRIGHT STREET',['Unit', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('COACH HOUSE WOBURN ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('104 GIBSON GARDENS',['StreetNumber', 'StreetName', 'StreetName']),
('SEEBECK HOUSE 1 SEEBECK PLACE KNOWLHILL',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('C/O ADDISON ACCOUNTS 26 HALSEY ROAD KEMPSTON',['CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('62-64 CHORLEY NEW ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('71-75 SHELTON STREET COVENT GARDEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('14 THE TRAMPERY ON THE GANTRY 1 WATERDEN ROAD',['Unit', 'Building', 'Building', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('UNIT 3 EARLSFIELD BUSINESS CENTRE 9 LYDDEN ROAD',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('124 CITY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('98 WOODHOUSE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('FLAT 2 36 BARNES HIGH STREET',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('HOLE FARM LORDINGS ROAD',['Others', 'Others', 'StreetName', 'StreetName']),
('128 CITY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('32-33 GOSFIELD STREET',['StreetNumber', 'StreetName', 'StreetName']),
('260 BOUNDARY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('6C THE BROADWAY FRIERN BARNET RD',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('SUITE 10-12 MEZZANINE FLOOR ROYAL LIVER BUILDING PIER HEAD',['Unit', 'Unit', 'CareOf', 'CareOf', 'Building', 'Building', 'Building', 'Locality', 'Locality']),
('13 DROVERS WAY SEER GREEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('27 MORTIMER STREET',['StreetNumber', 'StreetName', 'StreetName']),
('FLAT 41 WALLACE HOUSE GAYTON ROAD',['Unit', 'Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('65 BAYTREE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('3RD FLOOR 166 COLLEGE ROAD',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('93 TABERNACLE STREET',['StreetNumber', 'StreetName', 'StreetName']),
('UNIT 1 WATERSIDE OLD BOSTON ROAD',['Unit', 'Unit', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('130 MIRREN DRIVE HARDGATE',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('10 CANBERRA HOUSE CORBYGATE BUSINESS PARK',['Unit', 'Building', 'Building', 'Others', 'Others', 'Others']),
('58 SYCAMORE AVENUE WICKERSLEY',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('UNIT 17 ORBITAL 25 BUSINESS PARK DWIGHT ROAD',['Unit', 'Unit', 'Others', 'Others', 'Others', 'Others', 'StreetName', 'StreetName']),
('3 FISHER STREET CARLISLE',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('STELLA LUCA HOUSE UNIT 10 COLNE WAY COURT COLNE WAY',['CareOf', 'CareOf', 'CareOf', 'Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('2 PATTERTON RANGE STREET',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('CLYDE HOUSE REFORM ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('33 NEWALL STREET',['StreetNumber', 'StreetName', 'StreetName']),
('PIONEER HOUSE PIONEER BUSINESS PARK NORTH ROAD',['Building', 'Building', 'Others', 'Others', 'Others', 'StreetName', 'StreetName']),
('40 LLWYNGWERN PONTARDDULAIS',['StreetNumber', 'StreetName', 'Locality']),
('DERWENT BUSINESS CENTRE UNIT 22 CLARKE STREET',['Building', 'Building', 'Building', 'Unit', 'Unit', 'StreetName', 'StreetName']),
('C/O JACKSON & GRAHAM LAKE ROAD',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetName', 'StreetName']),
('16 PORT ARTHUR ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('UNIT 49 SECOND DROVE PETERBOROUGH',['Unit', 'Unit', 'StreetName', 'StreetName', 'Locality']),
('FLAT 3 BELL MOOR 1 PORTARLINGTON ROAD',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('1 CHARLOTTE CLOSE',['StreetNumber', 'StreetName', 'StreetName']),
('UNIT 1 ASH HILL COMMON BUNNY LAN SHERFIELD ENGLISH',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('7 SANDY COURT ASHLEIGH WAY LANGAGE BUSINESS PARK',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'Others', 'Others', 'Others']),
('MICHAEL HOUSE CASTLE STREET',['Building', 'Building', 'StreetName', 'StreetName']),
('UNIT DA2 SUTHERLAND HOUSE 43 SUTHERLAND ROAD',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('3RD FLOOR EASTGATE CASTLE STREET',['Floor', 'Floor', 'Building', 'StreetName', 'StreetName']),
('C/O LEIGH ADAMS LIMITED MAPLE HOUSE HIGH STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetName', 'StreetName']),
('BANK GREEN HOUSE FOX LANE HOLMESFIELD',['Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('64 NILE STREET',['StreetNumber', 'StreetName', 'StreetName']),
('FELIN BODUAN',['StreetName', 'Locality']),
('61 CHURCH STREET',['StreetNumber', 'StreetName', 'StreetName']),
('C/O JOHNSTON CARMICHAEL LLP BIRCHIN COURT 20 BIRCHIN LANE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('23 YEWDALE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('16 JUBILEE PARKWAY JUBILEE BUSINESS PARK',['StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others', 'Others']),
('LITTLEHAVEN HOUSE 24-26 LITTLEHAVEN LANE',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('QUEENSWAY HOUSE 11 QUEENSWAY',['Building', 'Building', 'StreetNumber', 'StreetName']),
('20-22 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('3175 CENTURY WAY THORPE PARK',['StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others']),
('SUITE G04 1 QUALITY COURT CHANCERY LANE',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('82 RIVERSIDE ESTATE SIR THOMAS LONGLEY ROAD MEDWAY CITY ESTATE',['Unit', 'Others', 'Others', 'StreetName', 'StreetName', 'StreetName', 'StreetName', 'Locality', 'Locality', 'Locality']),
('13 ARNOS ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('35 AVENUE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('137-139 WHITECROSS STREET',['StreetNumber', 'StreetName', 'StreetName']),
('FLAT 126 DAN COURT 5 LAKESIDE DRIVE PARK ROYAL',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others']),
('REGENCY HOUSE 45-51 CHORLEY NEW ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('SUITE 190 GROUND FLOOR OFFICES (VIA RECEPTION) PETERBOROUGH BUSINESS PARK LYNCH WOOD',['Unit', 'Unit', 'Floor', 'Floor', 'Others', 'Others', 'Others', 'Others', 'Others', 'Others', 'Locality', 'Locality']),
('RIVERSIDE HOUSE MELLOR STREET',['Building', 'Building', 'StreetName', 'StreetName']),
('1 THOMAS BUILDINGS NEW STREET',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('CHAPEL HOUSE 1 CHAPEL HILL',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('LONDON REGATTA CENTER DOCKSIDE ROAD',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('BRIDGE HOUSE 9-13 HOLBROOK LANE',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('1 ROSE COTTAGES LADYBARN LANE',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('10 SELBORNE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('FLAT 55 CHARLES GARDNER COURT HABERDASHER STREET',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('41 CLARENCE STREET',['StreetNumber', 'StreetName', 'StreetName']),
('1 THE FORUM MINERVA BUSINESS PARK',['Unit', 'Building', 'Building', 'Others', 'Others', 'Others']),
('NEMORA HOUSE WEST LOOE HILL NEMORA HOUSE',['Building', 'Building', 'StreetName', 'StreetName', 'StreetName', 'Building', 'Building']),
('127 METAL BOX FACTORY 30 GREAT GUILDFORD STREET',['Unit', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('5 MAHA BUILDING MERCHANT STREET',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('74 BRODRICK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('IBC 4-12 REGENT STREET ST. JAMES\'S',['CareOf', 'StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('IBC REX HOUSE ST. JAMES\'S 4-12 REGENT ST.',['CareOf', 'Building', 'Building', 'Locality', 'Locality', 'StreetNumber', 'StreetName', 'StreetName']),
('WHITEHAVEN COMMERCIAL PARK MORESBY PARKS',['Others', 'Others', 'Others', 'Locality', 'Locality']),
('7 REGENT ROAD HARBORNE',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('40 URQUHART ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('ST DENYS HOUSE 22 EAST HILL',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('2A POWELL STREET OLD TRAFFORD',['Unit', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('22 BOND STREET',['StreetNumber', 'StreetName', 'StreetName']),
('32 TREWARTON ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('NEWLANDS FARM DEWHURST LANE',['Building', 'Building', 'StreetName', 'StreetName']),
('FIRST FLOOR 17-19 FOLEY STREET',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('C/O 4 BARNARD CLOSE LITTLE CANFIELD',['CareOf', 'StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('AGS UNIT 1 CASTLE COURT 2 CASTLE GATE WAY',['CareOf', 'Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('297 STANNINGLEY ROAD BRAMLEY',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('55 HUNTERS HILL',['StreetNumber', 'StreetName', 'StreetName']),
('17 HEREWARD STREET',['StreetNumber', 'StreetName', 'StreetName']),
('SHERINGHS HOUSE PARK HOUSE LANE',['Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('HENSTAFF COURT LLANTRISANT ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('1 MOORHILLS CROFT SHIRLEY',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('38 MOUNT STREET',['StreetNumber', 'StreetName', 'StreetName']),
('C/O M SCRIVENS & CO LTD UNIT S THE WALLOWS INDUSTRIAL ESTATE FENS POOL AVENUE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'Unit', 'Unit', 'Others', 'Others', 'Others', 'Others', 'StreetName', 'StreetName', 'StreetName']),
('THE GARAGE ISHAM ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('44 GRAND PARADE',['StreetNumber', 'StreetName', 'StreetName']),
('1 WATLING STREET',['StreetNumber', 'StreetName', 'StreetName']),
('FIRST FLOOR TUDOR HOUSE 16 CATHEDRAL ROAD',['Floor', 'Floor', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('VICTORIA CHAMBERS ST RUNWALD STREET',['Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('CEDARVILLE WILLAND OLD VILLAGE',['Others', 'Locality', 'Locality', 'Locality']),
('BRO MEBYD PONTRHYDFENDIGAID CEREDIGION BRO MEBYD PONTRHYDFENDIGAID',['CareOf', 'CareOf', 'Locality', 'Locality', 'CareOf', 'CareOf', 'Locality']),
('13-15 MORNINGSIDE DRIVE',['StreetNumber', 'StreetName', 'StreetName']),
('30/32 TREBARWITH CRESECENT',['StreetNumber', 'StreetName', 'StreetName']),
('THE OLD VICARAGE VICARAGE ROAD RHYDYMWYN',['Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('RIVERBANK CHILDREN\'S CENTRE GILMOUR STREET',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('FLAT 5 23 HAMMELTON ROAD',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('12 ABBEY STREET',['StreetNumber', 'StreetName', 'StreetName']),
('2 ALDWYN CRESCENT HAZEL GROVE',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('24 SUFFOLK STREET',['StreetNumber', 'StreetName', 'StreetName']),
('29 WOODLAND AVENUE',['StreetNumber', 'StreetName', 'StreetName']),
('4 D AUCHINGRAMONT ROAD',['Unit', 'Unit', 'StreetName', 'StreetName']),
('2 GREENWAYS',['StreetNumber', 'StreetName']),
('CHEVIOT HOUSE BEAMINSTER WAY EAST KINGSTON PARK',['Building', 'Building', 'StreetName', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('ASH HOUSE BRECKENWOOD ROAD FULBOURN',['Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('TERCEL MEDICAL GROUP GALLWEY ROAD',['CareOf', 'CareOf', 'CareOf','StreetName', 'StreetName']),
('18 BADMINTON ROAD DOWNEND',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('34 BINGLEY ROAD SALTAIRE',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('10 CLOS MENTER EXCELSIOR INDUSTRIAL ESTATE GABALFA',['StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others', 'Others', 'Locality']),
('THE OLD RECTORY CHURCH STREET',['CareOf', 'CareOf', 'CareOf','StreetName', 'StreetName']),
('33 DENTAL CLOSE',['StreetNumber', 'StreetName', 'StreetName']),
('20 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('OFFICE 21 PEMBROKE HOUSE 8 ST. CHRISTOPHERS PLACE',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('54 WOOD STREET',['StreetNumber', 'StreetName', 'StreetName']),
('110A PARK LANE KNYPERSLEY',['Unit', 'StreetName', 'StreetName', 'Locality']),
('70 FLORENCE ROAD NEW CROSS',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('37 WARREN STREET',['StreetNumber', 'StreetName', 'StreetName']),
('41 KNOWSLEY STREET',['StreetNumber', 'StreetName', 'StreetName']),
('HANOVERGREEN COTTAGE HANOVER REDMARLEY',['Building', 'Building', 'Locality', 'Locality']),
('112 YARDLEY WOOD ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('16 WILLIAM GARDENS SMALLFIELD',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('11 TYLNEY CLOSE',['StreetNumber', 'StreetName', 'StreetName']),
('C/O THE OLD COUNCIL CHAMBERS HALFORD STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetName', 'StreetName']),
('48 - 52 PENNY LANE MOSSLEY HILL',['StreetNumber', 'StreetNumber', 'StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('LBP HOUSE EXCHANGE ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('104 GROVE ROAD ANSTY',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('13-15 HUNSLET ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('11 DEAKINS ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('GREENWAY FARM GOSBECK',['Building', 'Building', 'Locality']),
('33 MOAT FARM ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('105 MOSS LANE ORRELL PARK',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('38 KINGSWOOD',['StreetNumber', 'StreetName']),
('2ND FLOOR CROWN HOUSE 37 HIGH STREET',['Floor', 'Floor', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('9 EDWINS CLOSE',['StreetNumber', 'StreetName', 'StreetName']),
('8 & 9 EUROPE WAY MARVEJOLS BUSINESS PARK',['StreetNumber', 'StreetNumber', 'StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others', 'Others']),
('C/O MORR & CO LLP FIRST FLOOR CONNECT HOUSE 133-137 ALEXANDRA ROAD WIMBLEDON',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'Floor', 'Floor', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('5 MONTRAVE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('SB221 BUSINESS & TECHNOLOGY CENTRE UNIVERSITY OF WOLVERHAMPTON TELFORD CAMPUS',['Unit', 'Building', 'Building', 'Building', 'Building', 'Others', 'Others', 'Others', 'Others', 'Others']),
('JR BUSINESS CENTRE (NEXT TO POTTERY PUB) WAREHOUSE 3 TREFOREST INDUSTRIAL ESTATE',['Building', 'Building', 'Building', 'Building', 'Building', 'Building', 'Building', 'Unit', 'Unit', 'Others', 'Others', 'Others']),
('22 EVERGREEN DRIVE HAMPTON HARGATE',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('UNIT 5 51 PINFOLD STREET',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('167 GLOUCESTER TERRACE',['StreetNumber', 'StreetName', 'StreetName']),
('3 CASTLE COURT CARNEGIE CAMPUS',['StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others']),
('B1 BUSINESS CENTRE SUITE 206 DAVYFIELD ROAD',['Building', 'Building', 'Building', 'Unit', 'Unit', 'StreetName', 'StreetName']),
('108 RIDDLESDOWN ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('KEPPI HOUSE BLYTHSWOOD STREET',['Building', 'Building', 'StreetName', 'StreetName']),
('40 GLEBE FIELD',['StreetNumber', 'StreetName', 'StreetName']),
('23 DAVIS CLOSE LITTLE PAXTON',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('139 PLASHET GROVE',['StreetNumber', 'StreetName', 'StreetName']),
('5 HIGH STREET',['StreetNumber', 'StreetName', 'StreetName']),
('THE GARDEN SUITE 23 WESTFIELD PARK',['Unit', 'Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('1 THE GREEN BEESTON',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('9 DOWER ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('15 CROSS STREET NELSON',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('(ESTABLISHED 1897) DRY CLEANERS LIMITED WINCHESTER STREET',['Building', 'Building', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('ONE CENTRAL BOULEVARD BLYTHE VALLEY PARK SHIRLEY',['Building', 'Building', 'Building', 'Others', 'Others', 'Others', 'Locality']),
('905 HONEYSPOT ROAD STRATFORD',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('65 FROBISHER DRIVE',['StreetNumber', 'StreetName', 'StreetName']),
('671 ECCLES NEW RD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('SUITE 4 4 GIRO\'S PASSAGE',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('53 WILLINGDON ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('C/O RAYNER ESSEX LLP TAVISTOCK HOUSE SOUTH TAVISTOCK SQUARE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('202 WORSLEY ROAD SWINTON',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('265 BRANTINGHAM ROAD CHORLTON CUM HARDY',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality', 'Locality']),
('99 GRASMERE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('THE OCTAGON SUITE E2 2ND FLOOR MIDDLEBOROUGH',['Building', 'Building', 'Unit', 'Unit', 'Floor', 'Floor', 'Locality']),
('ZENITH HOUSE HIGHLANDS ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('ORCHARD COTTAGE BECK ORCHARD',['Building', 'Building', 'StreetName', 'StreetName']),
('C/O CLARKE BELL LIMITED 3RD FLOOR THE PINNACLE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Floor', 'Floor', 'Building', 'Building']),
('15 CWRT SYR DAFYDD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('306A GREEN LANE',['Unit', 'StreetName', 'StreetName']),
('20-22 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('25 HILLTOP COTTAGES DAISY HILL BACK LANE',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('2 FREDERICK STREET KINGS CROSS',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('87-89 WALTON STREET CHELSEA',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('UNIT 17 CHILTERN BUSINESS VILLAGE',['Unit', 'Unit', 'Others', 'Others', 'Others']),
('1 CASTERTON ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('12 BRUNEL BUSINESS COURT EASTERN WAY',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'StreetName', 'StreetName']),
('40 SWANFIELD LONG MELFORD',['StreetNumber', 'StreetName', 'Locality', 'Locality']),
('13 MYRTLE PLACE',['StreetNumber', 'StreetName', 'StreetName']),
('REGUS MANAGEMENT UK LTD FORSYTH HOUSE CROMAC SQUARE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetName', 'StreetName']),
('6 DOAGH ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('CALLIS MILL WOODLAND VIEW HALIFAX ROAD',['Building', 'Building', 'Locality', 'Locality', 'StreetName', 'StreetName']),
('APOLLO HOUSE HALLAM WAY WHITEHILLS BUSINESS PARK',['Building', 'Building', 'StreetName', 'StreetName', 'Others', 'Others', 'Others']),
('FLAT 6 14 ROYAL CRESCENT',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('40 ASHDALE CRESCENT DROYLSDEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('71-75 SHELTON STREET',['StreetNumber', 'StreetName', 'StreetName']),
('DEPARTMENT 5 51 PINFOLD STREET',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('AMS ACCOUNTANTS MEDICAL LTD 2ND FLOOR 9 PORTLAND STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('AMS ACCOUNTANTS MEDICAL LTD FLOOR 2 9 PORTLAND STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('20-22 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('11A PARK STREET',['StreetNumber', 'StreetName', 'StreetName']),
('71-75 SHELTON STREET COVENT GARDEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('141A WALKERN ROAD',['Unit', 'StreetName', 'StreetName']),
('FIRST FLOOR 36 THORPE WOOD BUSINESS PARK THORPE WOOD',['Floor', 'Floor', 'Unit', 'Others', 'Others', 'Others', 'Others', 'Locality', 'Locality']),
('C/O ANDERSON STRATHERN 1 RUTLAND COURT',['CareOf', 'CareOf', 'CareOf', 'Unit', 'Building', 'Building']),
('1 RUTLAND COURT',['Unit', 'Building', 'Building']),
('SAXON HOUSE DUKE STREET',['Building', 'Building', 'StreetName', 'StreetName']),
('272 BATH STREET',['StreetNumber', 'StreetName', 'StreetName']),
('133 MACMILLAN WAY HERITAGE PARK LONDON',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality', 'City']),
('2 HIGHAMS HILL GOSSOPS GREEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('C/O YMU BUSINESS MANAGEMENT LIMITED 180 GREAT PORTLAND STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('22 REGENT STREET',['StreetNumber', 'StreetName', 'StreetName']),
('73 SPRINGBANK ROAD ALYTH',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('THE ANNEXE WALTON LODGE HILLCLIFFE ROAD WALTON',['Unit', 'Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('11-13 HOCKERILL STREET',['StreetNumber', 'StreetName', 'StreetName']),
('6 RADLETT ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('78 ST. JOHNS CRESCENT',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('12 ST. GEORGE STREET LEVEL 4',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Floor', 'Floor']),
('BASEPOINT BUSINESS CENTRE C/O MEON ACCOUNTING LIMITED PREMIER WAY ABBEY PARK INDUSTRIAL ESTATE',['Building', 'Building', 'Building', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetName', 'StreetName', 'Others', 'Others', 'Others', 'Others']),
('14A FOREST GATE PEWSHAM',['Unit', 'StreetName', 'StreetName', 'Locality']),
('4 DOURO TERRACE',['StreetNumber', 'StreetName', 'StreetName']),
('21 BOULEVARD BARBES',['StreetNumber', 'StreetName', 'StreetName']),
('SUITE 306 STANMORE BUSINESS CENTRE HOWARD ROAD',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('UNIT 2 HARLEQUIN BUSINESS PARK KENNY HILL',['Unit', 'Unit', 'Others', 'Others', 'Others', 'Locality', 'Locality']),
('FORTIS INSOLVENCY LIMITED 683-693 WILMSLOW ROAD',['CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('24 AVERON RISE',['StreetNumber', 'StreetName', 'StreetName']),
('RODNEY CHAMBERS 40 RODNEY STREET',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('10 CAPEL CLOSE',['StreetNumber', 'StreetName', 'StreetName']),
('125 POYNTON ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('168 LEE LANE HORWICH',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('THE DOWNWOOD VINEYARD THE DOWNWOOD WIMBORNE ROAD',['Building', 'Building', 'Building', 'Locality', 'Locality', 'StreetName', 'StreetName']),
('7 BILLING ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('27 WOODFORD AVENUE PLYMPTON',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('1 THE OLD BANK CHAMBERS FORE STREET ST MARYCHURCH',['Unit', 'Building', 'Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('LEEBROOK BUSINESS CENTRE BURNLEY ROAD RAWTENSTALL',['Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('RESOURCE CENTRE GEDDING ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('STOKOE RODGER LLP UNIT 15 THE WATERMARK BANKSIDE',['CareOf', 'CareOf', 'CareOf', 'Unit', 'Unit', 'StreetName', 'StreetName', 'Building']),
('1 TEWKESBURY STREET',['StreetNumber', 'StreetName', 'StreetName']),
('86C MOOR GREEN & CO WATER STREET',['Unit', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetName', 'StreetName']),
('SUITE 306 STANMORE BUSINESS & INNOVATION CENTRE HOWARD ROAD',['Unit', 'Unit', 'Building', 'Building', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('27 OLD GLOUCESTER STREET',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('88 HILL VILLAGE ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('1 OLD COURT MEWS 311 CHASE ROAD',['Unit', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('10 WHARNCLIFFE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('37-39 OXFORD STREET (6TH FLOOR)',['StreetNumber', 'StreetName', 'StreetName', 'Floor', 'Floor']),
('18 PEMBROKE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('23 CHANTRY LANE',['StreetNumber', 'StreetName', 'StreetName']),
('58B HIGH STREET STONY STRATFORD',['Unit', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('9 WAYTE COURT RUDDINGTON',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('4-4A BLOOMSBURY SQUARE',['StreetNumber', 'StreetName', 'StreetName']),
('13 VILLAGE ROAD BEBINGTON',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('17 HAZEL WAY',['StreetNumber', 'StreetName', 'StreetName']),
('47 PRINCES AVENUE',['StreetNumber', 'StreetName', 'StreetName']),
('25 HIGH BANK ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('DELAWARE INTERCORP 113 BARKSDALE PROFESSIONAL CENTE',['CareOf', 'CareOf', 'Unit', 'Building', 'Building', 'Building']),
('38 SCHOOL LANE WILSFORD',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('1 PIRELLI WAY',['StreetNumber', 'StreetName', 'StreetName']),
('SOUTH LYNCH ESTATE OFFICE STANDON HURSLEY',['Building', 'Building', 'Building', 'Building', 'Locality', 'Locality']),
('07 BELL YARD',['StreetNumber', 'StreetName', 'StreetName']),
('2 WYCH ELM',['StreetNumber', 'StreetName', 'StreetName']),
('TORDOFF HOUSE APPERLEY BRIDGE',['Building', 'Building', 'Locality', 'Locality']),
('4-6 STATION ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('218 HIGH STREET',['StreetNumber', 'StreetName', 'StreetName']),
('THE TEMPLE 296 SHEFFIELD ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('BUILDING 3 BUILDING 3 EYAM GROVE GREAT MOOR',['Building', 'Building', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('3 EYAM GROVE GREAT MOOR',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('8 ANDOVER COURT 5 MINT STREET BETHNAL GREEN',['Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('86-90 PAUL STREET',['StreetNumber', 'StreetName', 'StreetName']),
('45 MOUNT PLEASANT',['StreetNumber', 'StreetName', 'StreetName']),
('PREMIER SUITE 4 CHURCHILL COURT 58 STATION ROAD',['Unit', 'Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('BCVS 23 QUEENS ROAD',['CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('5B KELSEY CLOSE ATTLEBOROUGH FIELDS IND ESTATE',['Unit', 'StreetName', 'StreetName', 'Others', 'Others', 'Others', 'Others']),
('BALLARDS LLP OAKMOORE COURT KINGSWOOD ROAD HAMPTON LOVETT',['CareOf', 'CareOf', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('33 LONGFORD AVENUE',['StreetNumber', 'StreetName', 'StreetName']),
('149 ST. PAULS AVENUE',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('29 FFORDD DEWI LLANGYFELACH',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('FERNDALE BUSINESS CENTRE EXETER STREET',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('C/O WILSON PITTS GLENDEVON HOUSE HAWTHORN PARK',['CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'StreetName', 'StreetName']),
('G4 GROSVENOR HOUSE 104 WATERGATE STREET',['Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('19 BRUNSTANE GARDENS',['StreetNumber', 'StreetName', 'StreetName']),
('C/O WALKER BROS (ELLAND) LTD AINLEYS INDUSTRIAL ESTATE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'Others', 'Others', 'Others']),
('64 ST. ANDREWS AVENUE',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('CROSS PARK COTTAGE ASHBURTON',['Building', 'Building', 'Building', 'Locality']),
('17 BOWENS HILL ROAD',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('25 HURSLEY ROAD CHANDLER\'S FORD',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('OFFICES 1 AND 2 1A KING STREET FARNWORTH',['Unit', 'Unit', 'Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('20-22 WENLOCK ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('129 STANNINGLEY ROAD ARMLEY',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('CHANDLER HOUSE 7 FERRY ROAD OFFICE PARK',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Others', 'Others']),
('UNION SUITE THE UNION BUILDING 51-59 ROSE LANE',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('FLAT 8 ALLOM HOUSE CLARENDON ROAD',['Unit', 'Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('FLAT 4 571 GREEN LANES',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('2 THE DEANS BRIDGE ROAD',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('2 THE DEANS BRIDGE ROAD BAGSHOT',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('9 PRINCES SQUARE',['StreetNumber', 'StreetName', 'StreetName']),
('3 CRAIGEND PLACE GLASGOW',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('FLAT 20 TANGMERE PLACE 2 GIBSON ROAD',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('142 DREWLY LANE',['StreetNumber', 'StreetName', 'StreetName']),
('STERLING OFFICES 30A MILL STREET',['Building', 'Building', 'Unit', 'StreetName', 'StreetName']),
('10A ARRAN LANE CHRYSTON',['Unit', 'StreetName', 'StreetName', 'Locality']),
('3RD FLOOR 86-90 PAUL STREET',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('PISYS HOUSE GRANDHOLM',['Building', 'Building', 'Locality']),
('132-134 GREAT ANCOATS STREET UNIT 620',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Unit', 'Unit']),
('1 NEVILLE DRIVE HAMPSTEAD GARDEN SUBBURB',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality', 'Locality']),
('1 BEAUCHAMP COURT 10 VICTORS WAY',['Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('10A ARRAN LANE CHRYSTON',['Unit', 'StreetName', 'StreetName', 'Locality']),
('3RD FLOOR 86-90 PAUL STREET',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('TOWN HALL TOWN HALL OLD BRISTOL RD',['Building', 'Building', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('1201 NEWFOUNDLAND 1',['Unit', 'Building', 'StreetNumber']),
('BLAKE TOWER FLOOR LG 12 BARBICAN',['Building', 'Building', 'Floor', 'Floor', 'Unit', 'Locality']),
('FLOOR 7 53 YIGAL ALON PO BOX 6706206',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName', 'POBox', 'POBox', 'POBox']),
('27 OLD GLOUCESTER STREET',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('22 SADLER GATE',['StreetNumber', 'StreetName', 'StreetName']),
('2 RODGERS STREET',['StreetNumber', 'StreetName', 'StreetName']),
('21 VILLA ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('36 THE GRESLEYS',['StreetNumber', 'StreetName', 'StreetName']),
('12 STONEBRIDGE ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('83 DUCIE STREET',['StreetNumber', 'StreetName', 'StreetName']),
('C/O CLARKE BELL LIMITED 3RD FLOOR THE PINNACLE 73 KING STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Floor', 'Floor', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('84 COMMERCE WAY',['StreetNumber', 'StreetName', 'StreetName']),
('LANGLEY HOUSE PARK ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('OFFICE 2 BROOK HOUSE 209 CRANBROOK ROAD',['Unit', 'Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('1 BEDE HOUSES STAPLEFORD ROAD STAPLEFORD',['Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('33 FLAT 2 SAMOS ROAD',['StreetNumber', 'Unit', 'Unit', 'StreetName', 'StreetName']),
('4 NEWMANS ROW LINCOLNS INN LINCOLN ROAD CRESSEX BUSINESS PARK',['Unit', 'Building', 'Building', 'Locality', 'Locality', 'StreetName', 'StreetName', 'Others', 'Others', 'Others']),
('132-134 GREAT ANCOATS STREET',['StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('30 BANKSIDE COURT STATIONFIELDS KIDLINGTON',['Unit', 'Building', 'Building', 'StreetName', 'Locality']),
('10 HIGH GABLES 1 SCOTTS AVENUE',['Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('SUITE 1 SECOND FLOOR EVERDENE HOUSE DEANSLEIGH ROAD',['Unit', 'Unit', 'Floor', 'Floor', 'Building', 'Building', 'StreetName', 'StreetName']),
('FINSGATE 5-7 CRANWOOD STREET',['Building', 'StreetNumber', 'StreetName', 'StreetName']),
('C J HOUSE 99A COBBOLD ROAD',['Building', 'Building', 'Building', 'Unit', 'StreetName', 'StreetName']),
('BENSON HOUSE 33 WELLINGTON STREET',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('C/O COUNTRYSIDE COMPANY SERVICES 386-388 PALATINE ROAD',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('9 BOND COURT LEEDS',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('ROYAL DOULTON BARLASTON',['CareOf', 'CareOf', 'Locality']),
('P.O BOX 730 20 FARRINGDON STREET',['POBox', 'POBox', 'POBox', 'StreetNumber', 'StreetName', 'StreetName']),
('PRICEWATERHOUSECOOPERS LLP BENSON HOUSE',['CareOf', 'CareOf', 'Building', 'Building']),
('P O BOX 810 FRIARY COURT',['POBox', 'POBox', 'POBox', 'POBox', 'Building', 'Building']),
('2ND FLOOR 95-107 LANCEFIELD STREET',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('SHEPCOTE LANE SHEFFIELD',['StreetName', 'StreetName', 'Locality']),
('1 APEX BUSINESS CENTRE BOSCOMBE ROAD',['Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('9TH FLOOR WEST BOWATER HOUSE',['Floor', 'Floor', 'Floor', 'Building', 'Building']),
('GRANT THORNTON HOUSE MELTON STREET',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('ELDRIDGE HOUSE 25 WINDSOR STREET',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('MENZIES CORPORATE RESTURCTURING 17-19 FOLEY STREET',['CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('COLMORE GATE 2 COLMORE ROW',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('C/O PRICEWATERHOUSECOOPERS 9 BOND STREET',['CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('UNIT 3 D31 PREMIER HOUSE ROLFE STREET',['Unit', 'Unit', 'Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('UNIT 3 CLIFTON BUSINESS PARK CHAMBERLAIN ROAD',['Unit', 'Unit', 'Others', 'Others', 'Others', 'StreetName', 'StreetName']),
('REAR OF 17 PLANTAGENET ROAD',['Unit', 'Unit', 'Unit', 'StreetName', 'StreetName']),
('1A CITY GATE 185 DYKE ROAD',['Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('3RD FLOOR 207 REGENT STREET',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('12 WATERSIDE CLOSE BORDESLEY GREEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('1 THE CENTRE',['Unit', 'Building', 'Building']),
('THE ESTATE OFFICE BROOK HALL LEIGHTON LANE EVERCREECH',['Unit', 'Unit', 'Unit', 'Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('C/O CLARK BUSINESS RECOVERY LIMITED 8 FUSION COURT',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('BECKET HOUSE 1 LAMBETH PALACE ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('BOWATER HOUSE KNIGHTSBRIDGE',['Building', 'Building', 'Locality']),
('P.O.BOX 17 SIM-CHEM HOUSE WARREN ROAD',['POBox', 'POBox', 'Building', 'Building', 'StreetName', 'StreetName']),
('ALBION WORKS SAVILE STREET',['CareOf', 'CareOf', 'StreetName', 'StreetName']),
('ERNST & YOUNG LLP 1 MORE LONDON PLACE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'Building', 'Building']),
('FOURTH FLOOR 130 WILTON ROAD',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName']),
('AQUIS HOUSE CLASKETGATE',['Building', 'Building', 'Locality']),
('C/O ARTHUR ANDERSEN & CO ST PAUL\'S HOUSE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'Building']),
('OURY CLARK HERSCHEL HOUSE',['CareOf', 'CareOf', 'Building', 'Building']),
('20/26 CURSTOR STREET LONDON',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('214 OXFORD STREET LONDON',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('THANET HOUSE 191-195 HIGH STREET',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('CHALFONT PARK GERRARDS CROSS',['Others', 'Others', 'Locality', 'Locality']),
('BRIDGE BUSINESS RECOVERY 3RD FLOOR 39-45',['CareOf', 'CareOf', 'CareOf', 'Floor', 'Floor', 'StreetNumber']),
('93 QUEEN STREET SHEFFIELD',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('67-69 MARROWAY STREET',['StreetNumber', 'StreetName', 'StreetName']),
('C/O PRICE & CO 65 BROAD GREEN',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('C/O AVF GROUP LTD DIXON STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetName', 'StreetName']),
('CROWN HOUSE BIRCH STREET',['Building', 'Building', 'StreetName', 'StreetName']),
('C/O TOUCHE ROSS & CO QUEEN ANNE HOUSE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'Building']),
('THE WILLOWS FARM HAWTON',['Others', 'Others', 'Others', 'Locality']),
('THE OLD CHURCH 48 VERULAM ROAD',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('WILLOW FARM NEWARK ROAD HAWTON',['Others', 'Others', 'StreetName', 'StreetName', 'Locality']),
('PR HOUSE HORTONWOOD 30',['Building', 'Building', 'StreetName', 'StreetName']),
('PO BOX 675 CASTLE WORKS EAST MOORS ROAD',['POBox', 'POBox', 'POBox', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('ATLAS HOUSE 15-25 EWELL ROAD',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('MARLBOROUGH HOUSE CHARNHAM LANE',['Building', 'Building', 'StreetName', 'StreetName']),
('DUNTON CAMPUS ARTERIAL ROAD',['Others', 'Others', 'StreetName', 'StreetName']),
('1 LOVE LANE LONDON',['StreetNumber', 'StreetName', 'StreetName','City']),
('1 WOODBOROUGH ROAD NOTTINGHAM',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('VICTORIA MILLS VICTORIA LANE GOLCAR',['Building', 'Building', 'StreetName', 'StreetName', 'Locality']),
('RENOLD HOUSE WYTHENSHAWE',['Building', 'Building', 'Locality']),
('31 CARLTON CRESCENT SOUTHAMPTON',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('ST JOHNS CENTRE 110 ALBION',['Building', 'Building', 'Building', 'StreetNumber', 'StreetName']),
('SIR HENRY PARKES ROAD CANLEY',['StreetName', 'StreetName', 'StreetName', 'StreetName', 'Locality']),
('41 MADISON STREET BLYTH',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('C/O INTERPATH LTD 10 FLEET PLACE',['CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName']),
('ERNST & YOUNG SILKHOUSE COURT',['CareOf', 'CareOf', 'CareOf', 'Building', 'Building']),
('AGA RANGEMASTER MEADOW LANE LONG EATON',['CareOf', 'CareOf', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('P/O BOX 99 HERON STREET HOLLINWOOD',['POBox', 'POBox', 'POBox', 'StreetName', 'StreetName', 'Locality']),
('STATION ROAD DORKING',['StreetName', 'StreetName', 'Locality']),
('30 UPHALL ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('9 MILNER FLATS KINGSWOOD STREET',['Unit', 'Building', 'Building', 'StreetName', 'StreetName']),
('BULMAN HOUSE REGENT CENTRE GOSFORTH',['Building', 'Building', 'Building', 'Building', 'Locality']),
('TOUCHE ROSS & CO ELEVEN ALBION ST',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetName', 'StreetName', 'StreetName']),
('EASTWOOD HALL MANSFIELD ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('8 BAKER STREET LONDON',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('ALLIED HOUSE 26 MANCHESTER SQUARE',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('ARGYLL HOUSE MILLINGTON ROAD',['Building', 'Building', 'StreetName', 'StreetName']),
('COLWYN CHAMBERS 19 YORK STREET',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('P.O.BOX 30 STOURPORT ROAD',['POBox', 'POBox', 'StreetName', 'StreetName']),
('5TH. FLOOR COLMORE GATE 2 COLMORE ROW',['Floor', 'Floor', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('POB 695 8 SALISBURY SQUARE',['POBox', 'POBox', 'StreetNumber', 'StreetName', 'StreetName']),
('TEMPLE COURT 35 COURT STREET',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('MANOR WAY HALESOWEN',['StreetName', 'StreetName', 'Locality']),
('TENON HOUSE FERRYBOAT LANE',['Building', 'Building', 'StreetName', 'StreetName']),
('43C LOCKBRIDGE COURT 7C WOODFIELD ROAD',['Unit', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('M J N HOUSE 11 DINGWALL RD',['Building', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('HURST MORRISON THOMSON 5 FAIRMILE',['CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName']),
('125 COLMORE ROW',['StreetNumber', 'StreetName', 'StreetName']),
('C/O DOUGLAS QUAY GROUP LIMITED 32 HIGH STREET OLD WHITTINGTON',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('2 LYGON PLACE EBURY STREET',['Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('NEALS CORNER SUITE 16 2 BATH ROAD',['Building', 'Building', 'Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName']),
('348 LYTHAM ROAD BLACKPOOL',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('PO BOX 810 HILL HOUSE 1 LITTLE NEW STREET',['POBox', 'POBox', 'POBox', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('136 WYCOMBE LANE WOOBURN GREEN',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('45 CHURCH STREET BIRMINGHAM',['StreetNumber', 'StreetName', 'StreetName', 'City']),
('NO. 1 DORSET STREET',['StreetNumber', 'StreetNumber', 'StreetName', 'StreetName']),
('ZOLFO COOPER TORONTO SQUARE',['CareOf', 'CareOf', 'StreetName', 'StreetName']),
('C/O DELOITTE & TOUCHE LLP HILL HOUSE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building']),
('11 ST JAMES\'S SQUARE MANCHESTER',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'City']),
('REGENT HOUSE CLINTON AVENUE',['Building', 'Building', 'StreetName', 'StreetName']),
('2ND FLOOR 19/24 SAINT GEORGE STREET',['Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('TOWER BRIDGE HOUSE ST KATHARINE\'S WAY',['Building', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName']),
('ATHELETIC STREET',['StreetName', 'StreetName']),
('SALVESEN HOUSE TOWNSEND DRIVE',['Building', 'Building', 'StreetName', 'StreetName']),
('HERTFORD ROAD HODDESDON',['StreetName', 'StreetName', 'Locality']),
('400 ALDRIDGE ROAD PERRY BARR',['StreetNumber', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('P O BOX 25 ORFORD LANE',['POBox', 'POBox', 'POBox', 'POBox', 'StreetName', 'StreetName']),
('174 BAKER ST ENFIELD',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('WETHERBY ROAD OSMANSTON PARK INDUSTRIAL EST.',['StreetName', 'StreetName', 'Others', 'Others', 'Others', 'Others']),
('765 FINCHLEY ROAD',['StreetNumber', 'StreetName', 'StreetName']),
('C/O MAZARS NEVILLE RUSSELL LANCASTER HOUSE',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building']),
('PO BOX 810 HILL HOUSE 1 LITTLE NEW STREET',['POBox', 'POBox', 'POBox', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName']),
('THE OLD HALSALL ARMS 2 SUMMERWOOD LANE HALSALL',['Building', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('C/O RSM ROBSON RHODES LLP CENTRE CITY TOWER 7 HILL STREET',['CareOf', 'CareOf', 'CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('C/O WYSEPLANT LTD CHAWSTON',['CareOf', 'CareOf', 'CareOf', 'Locality']),
('PARK HOUSE CLIFTON PARK',['Building', 'Building', 'Others', 'Others']),
('253 LEEK ROAD ENDON',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('MARMION HOUSE 3 COPENHAGEN STREET',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName']),
('007 ESCAPE ROOMS VICTORIA PASSAGE',['CareOf', 'CareOf', 'CareOf', 'StreetName', 'StreetName']),
('OFFICE 11 ROMNEY MARSH BUSINESS HUB MOUNTFIELD ROAD',['Unit', 'Unit', 'Building', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('OFFICE 119 JOHN ECCLES HOUSE ROBERT ROBINSON AVENUE OXFORD SCIENCE PARK',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName', 'StreetName', 'Others', 'Others', 'Others']),
('2 ADVENTURE PLACE HANLEY',['StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('UNIT 112325 13 FREELAND PARK WAREHAM ROAD POOLE DORSET',['Unit', 'Unit', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'StreetName', 'Locality', 'Locality']),
('UNIT D EAST FULTON FARM DARLUITH RD',['Unit', 'Unit', 'Building', 'Building', 'Building', 'StreetName', 'StreetName']),
('ALUM HOUSE 5 ALUM CHINE ROAD WESTBOURNE',['Building', 'Building', 'StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'Locality']),
('20 ENTERPRISE WAY FLAT 303',['StreetNumber', 'StreetName', 'StreetName', 'Unit', 'Unit']),
('THISTLE ACCOUNTANCY SERVICES WEST WING THIRD FLOOR PRESTONGRANGE HOUSE',['CareOf', 'CareOf', 'CareOf', 'Unit', 'Unit', 'Floor', 'Floor', 'Building', 'Building']),
('THYSSENKRUPP UK PLC FRIARS GATE (THIRD FLOOR) 1011 STRATFORD ROAD SHIRLEY',['CareOf', 'CareOf', 'CareOf', 'Building', 'Building', 'Floor', 'Floor', 'StreetNumber', 'StreetName', 'StreetName', 'Locality']),
('42 ST JAMES CRESCENT SWANSEA',['StreetNumber', 'StreetName', 'StreetName', 'StreetName', 'City']),
('WEDGNOCK LANE WARWICK',['StreetName', 'StreetName', 'City']),
('FLAT 11 SANDRINGHAM COURT SKERNE WALK',['Unit', 'Unit', 'Building', 'Building', 'StreetName', 'StreetName'])
]